/** TableauBuilder.scala Provides utility functions to build and manipulate
  * tableau trees for propositional logic. Authors:
  *   - Leslie Lucynda TINGUE
  *   - Bruno SANDELE
  *   - Dave Ronic DONKENG
  * version 1.0
  */
package project

import project.Formula
import project.EliminationRule.*
import project.{LazyTree, Tree, Status, Model}

object TableauBuilder:

  /** Build a semantic tableau (tree) for a set of propositional formulas.
    *
    * Recursive construction:
    *   1. If the current set of formulas contains a contradiction, return a
    *      closed leaf. 2. If no elimination rule can be applied, return an open
    *      leaf. 3. Otherwise, select a formula to eliminate and apply the
    *      corresponding elimination rule, producing a list of child formula
    *      sets. 4. Recursively build subtrees for each child set. 5. If no
    *      children are generated, return an open leaf.
    *
    * @param formulas
    *   The set of propositional formulas to build the tableau for.
    * @return
    *   A Tree representing the semantic tableau with branches and leaves marked
    *   as open or closed.
    */
  def semtab(formulas: Set[Formula]): Tree[Set[Formula]] =

    def loop(fs: Set[Formula]): Tree[Set[Formula]] =
      // 1. Contradiction → closed leaf
      if hasContradiction(fs) then Tree.Leaf(fs, Status.Closed)
      else
        // 2. Try to find a formula eligible for elimination
        FormulaToEliminate(fs) match
          case None =>
            // No more rules → open leaf
            Tree.Leaf(fs, Status.Open)

          case Some(f) =>
            val remaining = fs - f
            val (_, childrenSets) = applyEliminationRule(f, remaining)

            // 3. Build subtrees for each child generated by the rule
            val childTrees = childrenSets.map(loop)

            // 4. If no children exist → open leaf
            if childTrees.isEmpty then Tree.Leaf(fs, Status.Open)
            else Tree.Branch(fs, childTrees)

    loop(formulas)

  /** Build a lazy semantic tableau (LazyTree) for a set of propositional
    * formulas.
    *
    * This function constructs the tableau recursively:
    *   1. If the current set of formulas contains a contradiction, return a
    *      closed leaf. 2. If no elimination rule can be applied, return an open
    *      leaf. 3. Otherwise, select a formula to eliminate and apply the
    *      corresponding lazy elimination rule, generating a LazyList of child
    *      formula sets. 4. Recursively build subtrees for each child lazily
    *      using LazyList.
    *
    * Leaves store their status (Open or Closed), while branches contain a
    * LazyList of child subtrees.
    *
    * @param formulas
    *   Set of propositional formulas to build the tableau for
    * @return
    *   A LazyTree representing the semantic tableau, with lazy evaluation of
    *   subtrees
    */
  def lazysemtab(formulas: Set[Formula]): LazyTree[Set[Formula]] =

    def loop(fs: Set[Formula]): LazyTree[Set[Formula]] =
      if hasContradiction(fs) then
        LazyTree.Leaf(
          () => fs,
          () => Status.Closed
        )
      else
        FormulaToEliminate(fs) match
          case None =>
            LazyTree.Leaf(
              () => fs,
              () => Status.Open
            )
          case Some(f) =>
            LazyTree.Branch(
              () => fs,
              () => {
                val remaining = fs - f
                val (_, childrenSets) = applyEliminationRuleLazy(f, remaining)
                childrenSets.map(childSet => () => loop(childSet))
              }
            )

    loop(formulas)
